# Generated by Django 5.0.3 on 2024-08-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can view book'), ('can_create', 'can create book'), ('can_edit', 'can edit book'), ('can_delete', 'can delete book')]},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={},
        ),
        migrations.RemoveField(
            model_name='library',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='library',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='101', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
